import os


LOGS_DIR = config.get("logs_dir", "logs/nucflag")
BMKS_DIR = config.get("benchmarks_dir", "benchmarks/nucflag")
ALIGNER = config.get("aligner", "minimap2")
ALIGNER_OPTS = config.get("aligner_opts", "-y -a --eqx --cs -x lr:hqae -I8g")
SAMPLE_INFO = {sm["name"]: sm for sm in config["samples"]}


wildcard_constraints:
    sm="|".join(SAMPLE_INFO.keys()),


module Align:
    snakefile:
        "rules/Snakemake-Aligner/workflow/Snakefile"
    config:
        {
            **config,
            "aligner": ALIGNER,
            "aligner_opts": ALIGNER_OPTS,
            "logs_dir": LOGS_DIR,
            "benchmarks_dir": BMKS_DIR,
        }


use rule * from Align as aln_*


rule check_asm_nucflag:
    input:
        bam=ancient(rules.aln_merge_read_asm_alignments.output.alignment),
        fa=lambda wc: ancient(
            SAMPLE_INFO[str(wc.sm)]["asm_fa"]
            if SAMPLE_INFO[str(wc.sm)].get("asm_fa")
            else rules.aln_merge_asm_files.output.asm
        ),
        fai=lambda wc: ancient(
            SAMPLE_INFO[str(wc.sm)]["asm_fa"] + ".fai"
            if SAMPLE_INFO[str(wc.sm)].get("asm_fa")
            else rules.aln_merge_asm_files.output.idx
        ),
        # Optional arguments.
        regions=lambda wc: SAMPLE_INFO[str(wc.sm)].get("region_bed", []),
        config=lambda wc: SAMPLE_INFO[str(wc.sm)].get("config", []),
        ignore_regions=lambda wc: SAMPLE_INFO[str(wc.sm)].get("ignore_bed", []),
        overlay_regions=lambda wc: SAMPLE_INFO[str(wc.sm)].get("overlay_beds", []),
    output:
        plot_dir=(
            directory(os.path.join(config["output_dir"], "{sm}"))
            if config.get("output_plots")
            else []
        ),
        pileup_dir=(
            directory(os.path.join(config["output_dir"], "{sm}_pileup"))
            if config.get("output_pileup")
            else []
        ),
        misassemblies=os.path.join(
            config["output_dir"],
            "{sm}_misassemblies.bed",
        ),
        status=os.path.join(
            config["output_dir"],
            "{sm}_status.bed",
        ),
    params:
        preset=lambda wc: (
            f"-x {SAMPLE_INFO[str(wc.sm)]['preset']}"
            if SAMPLE_INFO[str(wc.sm)].get("preset")
            else ""
        ),
        regions=lambda wc, input: f"-b {input.regions}" if input.regions else "",
        config=lambda wc, input: f"-c {input.config}" if input.config else "",
        ignore_regions=lambda wc, input: (
            f"--ignore_regions {input.ignore_regions}" if input.ignore_regions else ""
        ),
        overlay_regions=lambda wc, input: (
            f"--overlay_regions {' '.join(input.overlay_regions)}"
            if input.overlay_regions
            else ""
        ),
        output_plots=lambda wc, output: (
            f"--output_plot_dir {output.plot_dir}"
            if config.get("output_plots")
            else ""
        ),
        output_pileup=lambda wc, output: (
            f"--output_pileup_dir {output.pileup_dir}"
            if config.get("output_pileup")
            else ""
        ),
    # LSF executor limits CPU usage based on threads.
    threads: config["processes_nucflag"]
    conda:
        "env/nucflag.yaml"
    resources:
        threads=config["threads_nucflag"],
        mem=config["mem_nucflag"],
    log:
        os.path.join(LOGS_DIR, "run_nucflag_{sm}.log"),
    benchmark:
        os.path.join(BMKS_DIR, "run_nucflag_{sm}.tsv")
    shell:
        """
        nucflag call \
        -i {input.bam} \
        -f {input.fa} \
        -o {output.misassemblies} \
        -s {output.status} \
        -t {resources.threads} \
        -p {threads} \
        {params.preset} \
        {params.config} \
        {params.regions} \
        {params.ignore_regions} \
        {params.overlay_regions} \
        {params.output_plots} \
        {params.output_pileup} &> {log}
        """


rule generate_ideogram:
    input:
        bed=rules.check_asm_nucflag.output.misassemblies,
        cytobands=lambda wc: (
            SAMPLE_INFO[str(wc.sm)]["cytobands"]
            if SAMPLE_INFO[str(wc.sm)].get("cytobands")
            else []
        ),
    output:
        plots=multiext(
            os.path.join(
                config["output_dir"],
                "{sm}_ideogram",
            ),
            png=".png",
            pdf=".pdf",
        ),
    log:
        os.path.join(LOGS_DIR, "ideogram_{sm}.log"),
    benchmark:
        os.path.join(BMKS_DIR, "ideogram_{sm}.tsv")
    params:
        output_prefix=lambda wc, output: os.path.splitext(output.plots[0])[0],
        cytobands=lambda wc, input: f"-c {input.cytobands}" if input.cytobands else "",
        filter_length=config.get("ideogram_filter_length", 10_000_000),
        track_height=config.get("ideogram_track_height", 2.0),
    shell:
        """
        nucflag ideogram \
        -i {input.bed} {params.cytobands} \
        -l {params.filter_length} \
        -t {params.track_height} \
        -o {params.output_prefix} 2> {log}
        """


rule generate_breakdown_plot:
    input:
        bed=rules.check_asm_nucflag.output.misassemblies,
    output:
        plots=multiext(
            os.path.join(
                config["output_dir"],
                "{sm}_breakdown",
            ),
            png=".png",
            pdf=".pdf",
        ),
    log:
        os.path.join(LOGS_DIR, "breakdown_plot_{sm}.log"),
    benchmark:
        os.path.join(BMKS_DIR, "breakdown_plot_{sm}.tsv")
    params:
        output_prefix=lambda wc, output: os.path.splitext(output.plots[0])[0],
        filter_length=config.get("breakdown_filter_length", 10_000_000),
        otype=config.get("breakdown_type", "percent"),
    shell:
        """
        nucflag breakdown \
        -i {input.bed} \
        -l {params.filter_length} \
        -t {params.otype} \
        -o {params.output_prefix} 2> {log}
        """


OUTPUTS = [expand(rules.check_asm_nucflag.output, sm=SAMPLE_INFO.keys())]


if config.get("output_ideogram"):
    OUTPUTS.append(expand(rules.generate_ideogram.output, sm=SAMPLE_INFO.keys()))


if config.get("output_breakdown"):
    OUTPUTS.append(expand(rules.generate_breakdown_plot.output, sm=SAMPLE_INFO.keys()))


rule nucflag:
    input:
        OUTPUTS,
    default_target: True
