
samples:
  - name: "K1463_2216_h2"
    asm_fa: /project/logsdon_shared/projects/asm-repair/fa/K1463_2216_hifiasm.fa
    read_dir: "/project/logsdon_shared/data/platinum_genomes/data/pacbio_hifi/K1463_2216/"
    read_ext: "fastq.gz"
    config: "config/nucflag.toml"
    region_bed: "/project/logsdon_shared/projects/asm-repair/fa/K1463_2216_ALR_regions.bed"
    ignore_bed: "config/nucflag_ignore.bed"
    overlay_beds: []

# winnowmap, pbmm2, or minimap2
# aligner_opts is optional. See README.md for defaults.
aligner: "winnowmap"
output_dir: "results/nucflag"
output_coverage: false
tmp_dir: "temp"
logs_dir: "logs/nucflag"
benchmarks_dir: "benchmarks/nucflag"
threads_aln: 8
mem_aln: 30G
processes_nucflag: 12
mem_nucflag: 50G
samtools_view_flag: 2308
