
samples:
  - name: "K1463_2216_h2"
    asm_fa: /project/logsdon_shared/projects/asm-repair/fa/K1463_2216_hifiasm.fa
    read_dir: "/project/logsdon_shared/data/platinum_genomes/data/pacbio_hifi/K1463_2216/"
    read_rgx: ".*\\.fastq.gz$"
    config: "config/nucflag.toml"
    preset: "hifi"
    region_bed: "/project/logsdon_shared/projects/asm-repair/fa/K1463_2216_ALR_regions.bed"
    overlay_beds: []

output_dir: "results/nucflag"
output_pileup: false
logs_dir: "logs/nucflag"
benchmarks_dir: "benchmarks/nucflag"
threads_aln: 8
mem_aln: 30G
processes_nucflag: 12
threads_nucflag: 2
mem_nucflag: 50G
samtools_view_flag: 2308
